<?php
$customers = $this->getData('customers');
$customer_by_column =  $this->getData('customer_by_column');
$customer_by_id =  $this->getData('customer_by_id');
?>

<?php include(BASE_DIR . '/templates/head.phtml') ?>

Ma view Customer Page : findAll
<ul>

<?php foreach ($customers as $customer) : ?>
    <li> Le client Mr/Mme <?= $customer->getLastname() ?> <?= $customer->getFirstname() ?> a <?= $customer->getAge() ?> ans </li>
<?php endforeach; ?>
</ul>

    Ma view Customer Page : findBy
    <ul>
<?php foreach ($customer_by_column as $customer) : ?>
    <li> Le client Mr/Mme <?= $customer->getLastname() ?> <?= $customer->getFirstname() ?> a <?= $customer->getAge() ?> ans </li>
<?php endforeach; ?>
    </ul>

    Ma view Customer Page : find($id)
    <ul>
        <li> Le client Mr/Mme <?= $customer->getLastname() ?> <?= $customer->getFirstname() ?> a <?= $customer->getAge() ?> ans </li>
    </ul>


<?php include(BASE_DIR . '/templates/footer.phtml') ?>