<?php
$todos = $this->getData('todos');
?>

<?php include(BASE_DIR . '/templates/head.phtml') ?>

    Ma view Todos Page : viewAll
    <ul>

        <?php foreach ($todos as $todo) : ?>
            <li> task n° <?= $todo->id?> from user<?= $todo->userId?> - need to do :  <?= $todo->title?> </li>
            <?php if($todo->completed) : ?>
                Status : Done
            <?php else :?>
                Status : ToDo
            <?php endif; ?>
        <?php endforeach; ?>
    </ul>

<?php include(BASE_DIR . '/templates/footer.phtml') ?>